// Route metadata for the app — every path is namespaced under /index.
// `label` is the professional, user-facing page title: it becomes the browser
// tab title ("<label> · Jelajah Emas") and the card title on the /index/sitemap map.
export const groups = [
  { key: 'auth', title: 'Autentikasi & Onboarding' },
  { key: 'home', title: 'Beranda' },
  { key: 'assets', title: 'Aset & Investasi' },
  { key: 'transactions', title: 'Transaksi & Riwayat' },
  { key: 'rewards', title: 'Reward & Poin' },
  { key: 'profile', title: 'Profil & Pengaturan' },
  { key: 'affiliate', title: 'Afiliasi' },
  { key: 'news', title: 'Berita' },
  { key: 'support', title: 'Bantuan & Informasi' },
  { key: 'landing', title: 'Landing Page' },
];

export const pages = [
  { slug: '/index/auth/welcome', path: '/index/auth/welcome', label: 'Selamat Datang', group: 'auth', component: 'WelcomePage' },
  { slug: '/index/auth/popup-awal', path: '/index/auth/popup-awal', label: 'Gabung Komunitas', group: 'auth', component: 'PopupAwal' },
  { slug: '/index/auth/notifikasi-login', path: '/index/auth/notifikasi-login', label: 'Notifikasi Login', group: 'auth', component: 'NotifikasiLogin' },
  { slug: '/index/auth/login', path: '/index/auth/login', label: 'Masuk', group: 'auth', component: 'Login' },
  { slug: '/index/auth/register-01', path: '/index/auth/register-01', label: 'Daftar Akun', group: 'auth', component: 'Register' },
  { slug: '/index/auth/register-02', path: '/index/auth/register-02', label: 'Daftar Akun', group: 'auth', component: 'Register' },
  { slug: '/index/auth/register-03', path: '/index/auth/register-03', label: 'Daftar Akun', group: 'auth', component: 'Register' },
  { slug: '/index/auth/register-04', path: '/index/auth/register-04', label: 'Daftar Akun', group: 'auth', component: 'Register' },
  { slug: '/index/auth/lupa-password', path: '/index/auth/lupa-password', label: 'Lupa Password', group: 'auth', component: 'LupaPassword' },
  { slug: '/index/auth/lupa-password-02', path: '/index/auth/lupa-password-02', label: 'Lupa Password', group: 'auth', component: 'LupaPassword' },
  { slug: '/index/auth/lupa-password-03', path: '/index/auth/lupa-password-03', label: 'Lupa Password', group: 'auth', component: 'LupaPassword' },
  { slug: '/index/auth/lupa-password-04', path: '/index/auth/lupa-password-04', label: 'Lupa Password', group: 'auth', component: 'LupaPassword' },
  { slug: '/index/home', path: '/index/home', label: 'Beranda', group: 'home', component: 'Home' },
  { slug: '/index/assets/alamat-pengiriman', path: '/index/assets/alamat-pengiriman', label: 'Alamat Pengiriman', group: 'assets', component: 'AlamatPengiriman' },
  { slug: '/index/assets/aset-03', path: '/index/assets/aset-03', label: 'Rencana Aktif', group: 'assets', component: 'Aset03' },
  { slug: '/index/assets/aset-saya-01', path: '/index/assets/aset-saya-01', label: 'Aset Saya', group: 'assets', component: 'AsetSaya' },
  { slug: '/index/assets/aset-saya-02', path: '/index/assets/aset-saya-02', label: 'Aset Saya', group: 'assets', component: 'AsetSaya' },
  { slug: '/index/assets/asset-01', path: '/index/assets/asset-01', label: 'Rencana Investasi', group: 'assets', component: 'Asset' },
  { slug: '/index/assets/asset-02', path: '/index/assets/asset-02', label: 'Detail Rencana', group: 'assets', component: 'Asset' },
  { slug: '/index/assets/cetak-emas-01', path: '/index/assets/cetak-emas-01', label: 'Cetak Emas', group: 'assets', component: 'CetakEmas' },
  { slug: '/index/assets/cetak-emas-02', path: '/index/assets/cetak-emas-02', label: 'Cetak Emas', group: 'assets', component: 'CetakEmas' },
  { slug: '/index/assets/cetak-emas-03', path: '/index/assets/cetak-emas-03', label: 'Cetak Emas', group: 'assets', component: 'CetakEmas' },
  { slug: '/index/assets/emas-digital', path: '/index/assets/emas-digital', label: 'Emas Digital', group: 'assets', component: 'EmasDigital' },
  { slug: '/index/assets/konfirmasi', path: '/index/assets/konfirmasi', label: 'Konfirmasi Aktivasi', group: 'assets', component: 'Konfirmasi' },
  { slug: '/index/profil/beri-rating', path: '/index/profil/beri-rating', label: 'Beri Rating', group: 'profile', component: 'BeriRating' },
  { slug: '/index/profil/beri-rating-02', path: '/index/profil/beri-rating-02', label: 'Beri Rating', group: 'profile', component: 'BeriRating' },
  { slug: '/index/transactions/detail-penarikan', path: '/index/transactions/detail-penarikan', label: 'Detail Penarikan', group: 'transactions', component: 'DetailPenarikan' },
  { slug: '/index/transactions/detail-penarikan-02', path: '/index/transactions/detail-penarikan-02', label: 'Detail Penarikan', group: 'transactions', component: 'DetailPenarikan' },
  { slug: '/index/transactions/detail-penarikan-03', path: '/index/transactions/detail-penarikan-03', label: 'Detail Penarikan', group: 'transactions', component: 'DetailPenarikan' },
  { slug: '/index/rewards/detail-riwayat-poin', path: '/index/rewards/detail-riwayat-poin', label: 'Detail Riwayat Poin', group: 'rewards', component: 'DetailRiwayatPoin' },
  { slug: '/index/transactions/isi-ulang', path: '/index/transactions/isi-ulang', label: 'Isi Ulang', group: 'transactions', component: 'IsiUlang' },
  { slug: '/index/transactions/loading-penarikan', path: '/index/transactions/loading-penarikan', label: 'Memproses Penarikan', group: 'transactions', component: 'LoadingPenarikan' },
  { slug: '/index/profil/pilih-bank', path: '/index/profil/pilih-bank', label: 'Pilih Bank', group: 'profile', component: 'PilihBank' },
  { slug: '/index/transactions/qris', path: '/index/transactions/qris', label: 'Pembayaran QRIS', group: 'transactions', component: 'Qris' },
  { slug: '/index/assets/riwayat-aset-saya', path: '/index/assets/riwayat-aset-saya', label: 'Riwayat Aset Saya', group: 'assets', component: 'RiwayatAsetSaya' },
  { slug: '/index/affiliate/riwayat-detail-komisi', path: '/index/affiliate/riwayat-detail-komisi', label: 'Riwayat Detail Komisi', group: 'affiliate', component: 'RiwayatDetailKomisi' },
  { slug: '/index/transactions/riwayat-isi-ulang', path: '/index/transactions/riwayat-isi-ulang', label: 'Riwayat Isi Ulang', group: 'transactions', component: 'RiwayatIsiUlang' },
  { slug: '/index/affiliate/riwayat-komisi', path: '/index/affiliate/riwayat-komisi', label: 'Riwayat Komisi', group: 'affiliate', component: 'RiwayatKomisi' },
  { slug: '/index/rewards/riwayat-lainnya', path: '/index/rewards/riwayat-lainnya', label: 'Riwayat Lainnya', group: 'rewards', component: 'RiwayatLainnya' },
  { slug: '/index/transactions/riwayat-penarikan', path: '/index/transactions/riwayat-penarikan', label: 'Riwayat Penarikan', group: 'transactions', component: 'RiwayatPenarikan' },
  { slug: '/index/rewards/riwayat-poin', path: '/index/rewards/riwayat-poin', label: 'Riwayat Poin', group: 'rewards', component: 'RiwayatPoin' },
  { slug: '/index/transactions/riwayat-transaksi', path: '/index/transactions/riwayat-transaksi', label: 'Riwayat Transaksi', group: 'transactions', component: 'RiwayatTransaksi' },
  { slug: '/index/transactions/tarik-dana-01', path: '/index/transactions/tarik-dana-01', label: 'Tarik Dana', group: 'transactions', component: 'TarikDana' },
  { slug: '/index/transactions/tarik-dana-02', path: '/index/transactions/tarik-dana-02', label: 'Tarik Dana', group: 'transactions', component: 'TarikDana' },
  { slug: '/index/transactions/tarik-dana-03', path: '/index/transactions/tarik-dana-03', label: 'Tarik Dana', group: 'transactions', component: 'TarikDana' },
  { slug: '/index/transactions/tarik-dana-04', path: '/index/transactions/tarik-dana-04', label: 'Tarik Dana', group: 'transactions', component: 'TarikDana' },
  { slug: '/index/transactions/virtual-account', path: '/index/transactions/virtual-account', label: 'Virtual Account', group: 'transactions', component: 'VirtualAccount' },
  { slug: '/index/rewards/absen-harian', path: '/index/rewards/absen-harian', label: 'Absen Harian', group: 'rewards', component: 'AbsenHarian' },
  { slug: '/index/rewards/misi', path: '/index/rewards/misi', label: 'Misi', group: 'rewards', component: 'Misi' },
  { slug: '/index/rewards/poin-mall-01', path: '/index/rewards/poin-mall-01', label: 'Poin Mall', group: 'rewards', component: 'PoinMall' },
  { slug: '/index/rewards/poin-mall-02', path: '/index/rewards/poin-mall-02', label: 'Poin Mall', group: 'rewards', component: 'PoinMall' },
  { slug: '/index/rewards/poin-mall-03', path: '/index/rewards/poin-mall-03', label: 'Poin Mall', group: 'rewards', component: 'PoinMall' },
  { slug: '/index/rewards/redeem-kode', path: '/index/rewards/redeem-kode', label: 'Redeem Kode', group: 'rewards', component: 'RedeemKode' },
  { slug: '/index/rewards/vip', path: '/index/rewards/vip', label: 'VIP', group: 'rewards', component: 'Vip' },
  { slug: '/index/rewards/vip-redeem-kode', path: '/index/rewards/vip-redeem-kode', label: 'Redeem Kode VIP', group: 'rewards', component: 'VipRedeemKode' },
  { slug: '/index/profil/edit', path: '/index/profil/edit', label: 'Edit Profil', group: 'profile', component: 'EditProfil' },
  { slug: '/index/profil/kartu-bank', path: '/index/profil/kartu-bank', label: 'Kartu Bank', group: 'profile', component: 'KartuBank' },
  { slug: '/index/profil/kartu-bank-02', path: '/index/profil/kartu-bank-02', label: 'Kartu Bank', group: 'profile', component: 'KartuBank' },
  { slug: '/index/profil/kartu-bank-03', path: '/index/profil/kartu-bank-03', label: 'Kartu Bank', group: 'profile', component: 'KartuBank' },
  { slug: '/index/profil/notifikasi', path: '/index/profil/notifikasi', label: 'Notifikasi', group: 'profile', component: 'MenuNotifikasi' },
  { slug: '/index/profil', path: '/index/profil', label: 'Profil', group: 'profile', component: 'Profil' },
  { slug: '/index/profil/setelan', path: '/index/profil/setelan', label: 'Setelan', group: 'profile', component: 'Setelan' },
  { slug: '/index/affiliate/detail-tim', path: '/index/affiliate/detail-tim', label: 'Detail Tim', group: 'affiliate', component: 'LihatDetailTim' },
  { slug: '/index/affiliate/tim-afiliasi', path: '/index/affiliate/tim-afiliasi', label: 'Tim Afiliasi', group: 'affiliate', component: 'TimAfiliasi' },
  { slug: '/index/berita', path: '/index/berita', label: 'Berita', group: 'news', component: 'Berita' },
  { slug: '/index/berita/detail', path: '/index/berita/detail', label: 'Detail Berita', group: 'news', component: 'DetailBerita' },
  { slug: '/index/support/hubungi-cs', path: '/index/support/hubungi-cs', label: 'Hubungi CS', group: 'support', component: 'HubungiCs' },
  { slug: '/index/support/kebijakan-privasi', path: '/index/support/kebijakan-privasi', label: 'Kebijakan Privasi', group: 'support', component: 'KebijakanPrivasi' },
  { slug: '/index/support/livechat', path: '/index/support/livechat', label: 'Live Chat', group: 'support', component: 'Livechat' },
  { slug: '/index/support/pertanyaan-umum', path: '/index/support/pertanyaan-umum', label: 'Pertanyaan Umum', group: 'support', component: 'PertanyaanUmum' },
  { slug: '/index/support/syarat-dan-ketentuan', path: '/index/support/syarat-dan-ketentuan', label: 'Syarat & Ketentuan', group: 'support', component: 'SyaratDanKetentuan' },
  { slug: '/index/support/tentang-kami', path: '/index/support/tentang-kami', label: 'Tentang Kami', group: 'support', component: 'TentangKami' },
  { slug: '/index/landing', path: '/index/landing', label: 'Website Resmi', group: 'landing', component: 'LandingPagePerusahaan' },
];
